### PR TITLE
fix: handle testing environment using defaults

### LINKED ISSUE #22: Playwright tests fail as need default feature flags
### Description

When running the automated tests on GitHub Actions, we do not want to load tests Flagsmith's servers, so we will run with default flags

> You can run in offline mode, local evaluation mode or just use defaults

Discussion from the Flagsmith Discord server.

> [!NOTE]
> Playwright GitHub Action will fail until this is fixed

What I am trying to use
https://github.com/EddieHubCommunity/HealthCheck/blob/23d35eef3210cf07c6200e5a1c1b833cb1b485f3/src/config/flagsmith.js#L14-L17

Here are the official docs
https://docs.flagsmith.com/clients/javascript#providing-default-flags

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dan-mba**
## Fixes Issue
Closes #22 

## Changes proposed
Use try/catch to ignore flagsmith init error & use defaults
Don't run playwright as pre-commit as errors are hidden when using git in IDE (VSCode)

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

File: src/config/flagsmith.js [hunk 1]
```diff
@@ -5,18 +5,22 @@ import config from "./flagsmith.json";
 export default async function flagsmith() {
   const defaults = Object.fromEntries(
     config.map((flag) => [
-      [flag.name],
+      flag.name,
```
Comment (eddiejaoude) [inline src/config/flagsmith.js:8]: oh good spot 💯

File: src/config/flagsmith.js [hunk 2]
```diff
@@ -5,18 +5,22 @@ import config from "./flagsmith.json";
...
-  });
+  try {
+    await flagsmith.init({
+      environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID,
+      defaultFlags: defaults,
+    });
+  } catch {
+    // Handle unable to connect to Flagsmith or not having valid environment
+    // Defaults will be used
+  }
```
Comment (eddiejaoude) [inline src/config/flagsmith.js:22]: oh I see 😱

**Review by eddiejaoude — APPROVED** [review]
Thank you!
